# RECOMMENDATION SYSTEM USING MATRIX FACTORISATION(SVD)

Singular value decomposition (SVD) is a collaborative filtering method for movie recommendation.

In [1]:
#Import Libraries
import numpy as np
import pandas as pd

In [2]:
#import movies dataset
MOVIES=pd.read_csv("movies.csv")

In [3]:
MOVIES

movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
62418   209157                           We (2018)   
62419   209159           Window of the Soul (2001)   
62420   209163                    Bad Poems (2018)   
62421   209169                 A Girl Thing (2001)   
62422   209171      Women of Devil's Island (1962)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
62418                                        Drama  
62419                                  Documentary  
62420                                 Comedy|Drama  
62421                           (no genres listed)  
62422                       Action|Adventure|Drama  

[62423 rows x 3 columns]

In [4]:
#Import Ratings dataset
RATINGS=pd.read_csv("ratings.csv")

In [5]:
RATINGS

userId  movieId  rating   timestamp
0             1      296     5.0  1147880044
1             1      306     3.5  1147868817
2             1      307     5.0  1147868828
3             1      665     5.0  1147878820
4             1      899     3.5  1147868510
...         ...      ...     ...         ...
1048570    7045     4447     3.5  1164258032
1048571    7045     4720     4.0  1164257756
1048572    7045     4857     4.0  1164242753
1048573    7045     4886     5.0  1168033506
1048574    7045     4896     4.0  1164122301

[1048575 rows x 4 columns]

In [6]:
#MERGING MOVIES and RATINGS
MOVIES_RATINGS=pd.merge(RATINGS,MOVIES,how='outer',on='movieId')

In [7]:
MOVIES_RATINGS

userId  movieId  rating     timestamp  \
0           1.0      296     5.0  1.147880e+09   
1           3.0      296     5.0  1.439474e+09   
2           4.0      296     4.0  1.573939e+09   
3           5.0      296     4.0  8.307862e+08   
4           7.0      296     4.0  8.354447e+08   
...         ...      ...     ...           ...   
1088753     NaN   209155     NaN           NaN   
1088754     NaN   209157     NaN           NaN   
1088755     NaN   209159     NaN           NaN   
1088756     NaN   209169     NaN           NaN   
1088757     NaN   209171     NaN           NaN   

                                  title                       genres  
0                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller  
1                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller  
2                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller  
3                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller  
4                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller  
...                                 ...                          ...  
1088753      Santosh Subramaniam (2008)        Action|Comedy|Romance  
1088754                       We (2018)                        Drama  
1088755       Window of the Soul (2001)                  Documentary  
1088756             A Girl Thing (2001)           (no genres listed)  
1088757  Women of Devil's Island (1962)       Action|Adventure|Drama  

[1088758 rows x 6 columns]

In [8]:
#Create a cross_Table for with user_id,movie_id having values of ratings
Cross_Table=RATINGS.pivot(index = 'userId', columns ='movieId', values = 'rating').fillna(0)

In [9]:
Cross_Table

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           3.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           3.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
7041        4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7042        4.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7043        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7044        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7045        4.5     0.0     0.0     0.0     0.0     0.0     4.0     0.0   

movieId  9       10      ...  207642  207830  207890  208002  208080  208112  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
7041        0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
7042        0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
7043        0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
7044        0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
7045        0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  208737  208793  208939  209163  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
7041        0.0     0.0     0.0     0.0  
7042        0.0     0.0     0.0     0.0  
7043        0.0     0.0     0.0     0.0  
7044        0.0     0.0     0.0     0.0  
7045        0.0     0.0     0.0     0.0  

[7045 rows x 22240 columns]

In [10]:
#Convert it to matrix
Cross_Table_matrix=np.asmatrix(Cross_Table)

In [11]:
Cross_Table_matrix

matrix([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [3.5, 0. , 0. , ..., 0. , 0. , 0. ],
        [4. , 0. , 0. , ..., 0. , 0. , 0. ],
        ...,
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0. , 0. , 0. ],
        [4.5, 0. , 0. , ..., 0. , 0. , 0. ]])

In [12]:
#Take the mean of all ratings for each user by taking mean of cross table alomg the coloumn
user_mean_ratings=np.mean(Cross_Table_matrix,axis=1)

In [13]:
user_mean_ratings

matrix([[0.0120054 ],
        [0.03003597],
        [0.10906025],
        ...,
        [0.00364209],
        [0.00451888],
        [0.03194694]])

In [14]:
#Demean or normalise the data
Demeaned_Data=Cross_Table_matrix-user_mean_ratings

In [15]:
Demeaned_Data

matrix([[-1.20053957e-02, -1.20053957e-02, -1.20053957e-02, ...,
         -1.20053957e-02, -1.20053957e-02, -1.20053957e-02],
        [ 3.46996403e+00, -3.00359712e-02, -3.00359712e-02, ...,
         -3.00359712e-02, -3.00359712e-02, -3.00359712e-02],
        [ 3.89093975e+00, -1.09060252e-01, -1.09060252e-01, ...,
         -1.09060252e-01, -1.09060252e-01, -1.09060252e-01],
        ...,
        [-3.64208633e-03, -3.64208633e-03, -3.64208633e-03, ...,
         -3.64208633e-03, -3.64208633e-03, -3.64208633e-03],
        [-4.51888489e-03, -4.51888489e-03, -4.51888489e-03, ...,
         -4.51888489e-03, -4.51888489e-03, -4.51888489e-03],
        [ 4.46805306e+00, -3.19469424e-02, -3.19469424e-02, ...,
         -3.19469424e-02, -3.19469424e-02, -3.19469424e-02]])

In [16]:
#Matrix Fcatorisation using singular value decomposition
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(Demeaned_Data, k = 50)

In [17]:
U

array([[ 0.00223357,  0.00027924, -0.01073208, ..., -0.00360237,
         0.00178407, -0.00247682],
       [ 0.00730199,  0.0026073 , -0.0113278 , ...,  0.00374482,
        -0.00049575, -0.01484951],
       [-0.02178268, -0.01300609,  0.01664966, ...,  0.00425737,
         0.05567426, -0.0290949 ],
       ...,
       [ 0.00749583, -0.00281318, -0.00670246, ...,  0.01292746,
        -0.00433861, -0.0033447 ],
       [ 0.00628369,  0.00448363, -0.01079252, ..., -0.00040216,
         0.0007863 , -0.00270881],
       [ 0.01312836, -0.01227214,  0.00588613, ...,  0.00193466,
        -0.0165207 , -0.01811334]])

In [18]:
sigma

array([ 149.23081749,  149.9616989 ,  150.88970148,  151.96965651,
        153.08479819,  153.57009391,  154.75062852,  155.9708355 ,
        156.87677519,  159.62519076,  159.98626679,  162.60451105,
        165.38856462,  166.32790259,  168.60009774,  171.19435207,
        171.61154695,  175.81605583,  176.68506767,  179.15204926,
        182.10722099,  185.19945018,  186.83527539,  188.91074273,
        189.01028274,  192.23930625,  197.4451442 ,  200.07512855,
        201.57554553,  208.30612206,  215.20784532,  218.68341617,
        224.3457981 ,  229.31104898,  236.5648396 ,  244.21424714,
        260.83331086,  273.90709374,  279.76115238,  283.41952799,
        289.90296721,  321.01731319,  340.92924528,  408.26795535,
        413.42713202,  426.81920933,  507.79019093,  562.81629002,
        761.12821077, 1547.99009699])

In [19]:
#Sigma returned should be converted to daigonal matrix
sigma=np.diag(sigma)

In [20]:
sigma

array([[ 149.23081749,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,  149.9616989 ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,  150.88970148, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [   0.        ,    0.        ,    0.        , ...,  562.81629002,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
         761.12821077,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        , 1547.99009699]])

In [21]:
Vt

array([[ 5.17757812e-02,  1.91728412e-03, -1.46158273e-02, ...,
        -2.15802352e-03,  1.38185373e-03,  1.11393548e-03],
       [ 7.78990449e-03, -7.59544410e-03, -8.89135236e-03, ...,
        -1.44359942e-03, -3.96797589e-04, -8.64849073e-04],
       [-5.23815043e-03, -2.67193584e-02,  1.10998110e-02, ...,
         4.26680912e-03,  3.24524910e-04, -1.51368359e-03],
       ...,
       [ 5.28805689e-02,  6.03224980e-02,  2.39804572e-02, ...,
         5.89485519e-04,  5.27999439e-04,  4.88602953e-04],
       [-2.09800539e-02, -1.23473716e-02, -2.56173366e-02, ...,
         1.52233166e-04,  6.26498403e-05,  4.22946997e-05],
       [-8.18429736e-02, -3.33898060e-02, -1.17845867e-02, ...,
         1.99257458e-03,  1.99799963e-03,  2.03766542e-03]])

In [35]:
#Vt.shape

In [22]:
# Predict the movie rating for every user
predicted_ratings=np.dot(np.dot(U, sigma), Vt) + user_mean_ratings.reshape(-1, 1)

In [23]:
predicted_ratings

matrix([[ 7.94203978e-01, -1.17510749e-01, -4.87406187e-02, ...,
         -1.19889490e-02, -4.99074051e-03,  6.38123168e-03],
        [ 3.65408698e+00,  5.86849481e-01,  8.43516038e-02, ...,
          1.03276960e-02, -2.01852557e-02,  6.32875730e-03],
        [ 1.97377853e+00,  3.96332955e-01, -3.96386204e-01, ...,
         -3.11971711e-02, -7.64551504e-03, -1.80537351e-02],
        ...,
        [ 1.46048491e-01,  8.28993148e-02, -3.43333963e-01, ...,
         -1.23172719e-02, -4.72145029e-04,  1.47058713e-03],
        [ 4.52802199e-01,  2.14162009e-01,  1.09776505e-01, ...,
         -1.67210476e-02, -4.49719773e-03,  9.49019070e-03],
        [ 5.00250058e+00,  1.44563894e+00,  6.74467020e-01, ...,
          5.02389122e-03,  2.62352742e-03,  6.26469119e-03]])

In [24]:
#Construct preditced matrices
Predicted_Matrix= pd.DataFrame(data=predicted_ratings,columns=Cross_Table.columns)

In [25]:
Predicted_Matrix

movieId    1         2         3         4         5         6         7       \
0        0.794204 -0.117511 -0.048741 -0.030539 -0.033550 -0.231152  0.126645   
1        3.654087  0.586849  0.084352 -0.093424 -0.101964  0.326946  0.326248   
2        1.973779  0.396333 -0.396386 -0.139322 -0.161286  0.536361  0.054660   
3        2.573367  0.227047 -0.128098 -0.058746 -0.018811  0.280404  0.221227   
4        4.295581  0.762589  1.384023  0.075727  1.025965  1.497588  0.966642   
...           ...       ...       ...       ...       ...       ...       ...   
7040     3.493140 -0.229389  0.176393 -0.024049 -0.161903  0.016298 -0.032456   
7041     3.371337  0.332534  0.112413 -0.099492  0.148472  0.676764  0.173384   
7042     0.146048  0.082899 -0.343334 -0.119373 -0.372707  0.663160 -0.419719   
7043     0.452802  0.214162  0.109777  0.025448  0.057538  0.244310  0.104571   
7044     5.002501  1.445639  0.674467 -0.026010  0.552016  0.340908  1.745139   

movieId    8         9         10      ...    207642    207830    207890  \
0       -0.017733 -0.004234  0.133950  ... -0.006063 -0.002026 -0.008895   
1        0.095518 -0.048356  0.840146  ... -0.001769 -0.019375 -0.010207   
2       -0.197397 -0.208810 -0.615998  ... -0.033022  0.015837 -0.029381   
3       -0.064724 -0.055982  0.520505  ... -0.007620 -0.000310  0.004310   
4       -0.032700  0.439513  1.157365  ... -0.007481 -0.004687 -0.001157   
...           ...       ...       ...  ...       ...       ...       ...   
7040    -0.077216 -0.046133 -0.514355  ... -0.006158 -0.013665 -0.009932   
7041    -0.002338  0.039934  1.196725  ... -0.002234  0.001923 -0.002351   
7042    -0.114646 -0.075342  1.176006  ... -0.000839 -0.003311  0.002817   
7043     0.055088  0.009386  0.036595  ... -0.002147 -0.004061 -0.002109   
7044     0.161437 -0.085580  1.588029  ...  0.009386  0.005874 -0.000685   

movieId    208002    208080    208112    208737    208793    208939    209163  
0       -0.005748  0.003768 -0.004638 -0.003798 -0.011989 -0.004991  0.006381  
1       -0.008758  0.006939  0.003917 -0.005292  0.010328 -0.020185  0.006329  
2       -0.020271 -0.008385 -0.031978 -0.020568 -0.031197 -0.007646 -0.018054  
3        0.007121  0.003513 -0.014110 -0.002357 -0.010292 -0.007028  0.010657  
4       -0.004380 -0.004883  0.002864 -0.002629  0.003779 -0.004680  0.000180  
...           ...       ...       ...       ...       ...       ...       ...  
7040    -0.009966 -0.006311  0.002722 -0.008577 -0.014624 -0.012764 -0.008554  
7041    -0.001509 -0.007099 -0.004394 -0.002200 -0.001746 -0.004909 -0.003701  
7042    -0.000597 -0.000801 -0.003272  0.000094 -0.012317 -0.000472  0.001471  
7043     0.000556  0.006356 -0.004093 -0.002150 -0.016721 -0.004497  0.009490  
7044    -0.001712  0.000668  0.004497  0.002080  0.005024  0.002624  0.006265  

[7045 rows x 22240 columns]

In [26]:
#Creating a function that will return recommended Movies and User Data
def recommend_movies(preds_df, userID, movies_df, original_ratings_df, num_of_recomd=5):
    # Get and sort the user's predictions
    user_row_number = userID - 1 # As UserID starts at 1, not 0
    #Get the information from predicted Matrix of that paricular User
    sorted_user_predictions = preds_df.iloc[user_row_number].sort_values(ascending=False)
    
    # Get the user's data from ratings datset by comparing the userid and then merge in the movies dataframe on basis of movieID.
    user_data = original_ratings_df[original_ratings_df.userId == (userID)]
    user_full_Data= (user_data.merge(movies_df, how = 'left', left_on = 'movieId', right_on = 'movieId').
                     sort_values(['rating'], ascending=False))
    
    
    #Printing the prdicted Movies
    print(f"User {userID} has already rated {user_full_Data.shape[0]} movies")
    print(f"Recommending the top {num_of_recomd} movies that you may like")
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[movies_df['movieId'].isin(user_full_Data['movieId'])].
            merge(pd.DataFrame(sorted_user_predictions).reset_index(), how="outer").
        sort_values(user_row_number,ascending=False).   #sorting values on the basis of ratings
                      iloc[:num_of_recomd, :])
    recommendations=recommendations.rename(columns={user_row_number:"Top Ratings"})
    return user_full_Data, recommendations

already_rated, recommd = recommend_movies(Predicted_Matrix, 837,MOVIES ,RATINGS, 10)

User 837 has already rated 204 movies
Recommending the top 10 movies that you may like


In [27]:
already_rated

userId  movieId  rating   timestamp  \
75      837     1784     5.0  1160159579   
85      837     2291     5.0  1160159744   
194     837    40815     5.0  1160159375   
49      837     1196     5.0  1160159539   
186     837    30892     5.0  1160160269   
..      ...      ...     ...         ...   
162     837     6796     0.5  1160160793   
157     837     6377     0.5  1160159472   
155     837     6283     0.5  1160161021   
144     837     4993     0.5  1160159198   
0       837        1     0.5  1160159624   

                                                 title  \
75                           As Good as It Gets (1997)   
85                          Edward Scissorhands (1990)   
194         Harry Potter and the Goblet of Fire (2005)   
49   Star Wars: Episode V - The Empire Strikes Back...   
186                 In the Realms of the Unreal (2004)   
..                                                 ...   
162                             Boyz N the Hood (1991)   
157                                Finding Nemo (2003)   
155  Cowboy Bebop: The Movie (Cowboy Bebop: Tengoku...   
144  Lord of the Rings: The Fellowship of the Ring,...   
0                                     Toy Story (1995)   

                                          genres  
75                          Comedy|Drama|Romance  
85                         Drama|Fantasy|Romance  
194              Adventure|Fantasy|Thriller|IMAX  
49                       Action|Adventure|Sci-Fi  
186                        Animation|Documentary  
..                                           ...  
162                                  Crime|Drama  
157          Adventure|Animation|Children|Comedy  
155             Action|Animation|Sci-Fi|Thriller  
144                            Adventure|Fantasy  
0    Adventure|Animation|Children|Comedy|Fantasy  

[204 rows x 6 columns]

In [28]:
recommd

movieId                                              title  \
59      1270                          Back to the Future (1985)   
101     2762                            Sixth Sense, The (1999)   
53      1210  Star Wars: Episode VI - Return of the Jedi (1983)   
14       260          Star Wars: Episode IV - A New Hope (1977)   
110     2959                                  Fight Club (1999)   
17       318                   Shawshank Redemption, The (1994)   
107     2858                             American Beauty (1999)   
22       356                                Forrest Gump (1994)   
16       296                                Pulp Fiction (1994)   
49      1196  Star Wars: Episode V - The Empire Strikes Back...   

                          genres  Top Ratings  
59       Adventure|Comedy|Sci-Fi     5.272649  
101         Drama|Horror|Mystery     5.238185  
53       Action|Adventure|Sci-Fi     5.016489  
14       Action|Adventure|Sci-Fi     4.970612  
110  Action|Crime|Drama|Thriller     4.864219  
17                   Crime|Drama     4.821672  
107                Drama|Romance     4.790511  
22      Comedy|Drama|Romance|War     4.616903  
16   Comedy|Crime|Drama|Thriller     4.490632  
49       Action|Adventure|Sci-Fi     4.399958

In [29]:
USER_RATINGS=already_rated["rating"].iloc[:10]# as we have taken 10 number of recommendation
USER_RATINGS=USER_RATINGS.array
PREDICTED_RATINGS=recommd["Top Ratings"]
PREDICTED_RATINGS=PREDICTED_RATINGS.array

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
np.sqrt(mean_squared_error(USER_RATINGS,PREDICTED_RATINGS))

0.31505516677985285

#The lower the RMSE the better is the model
#RMSE<0.5 reflects the better ability of predecting the data accurately